version: '3.8'
services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
        depends_on:
            - postgres
            - elasticsearch
            - rabbitmq
        environment:
            - DATABASE_URL=postgresql://user:password@postgres:5432/kamu_portal
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - AWS_ACCESS_KEY_ID=YOUR_KEY
            - AWS_SECRET_ACCESS_KEY=YOUR_SECRET
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=kamu_portal
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    elasticsearch:
        image: elasticsearch:8.10.0
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
volumes:
    postgres_data:
